export const APPLY_CONSTRAINT = 'APPLY_CONSTRAINT';
export const CONFIGURE_CONSTRAINTS = 'CONFIGURE_CONSTRAINTS';
// export const CONFIGURE_OPTION = 'CONFIGURE_OPTION';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
